On :
     Push :
          Branches :
             - main
     Pull _ request:
        Branches 
           - main
jobs :
  Build :

         Runs - on : Ubuntu - latest

         Strategy :
              Matrix : 
                  Node - version : [20.x] 
   
          Steps
          - name : checkout repository 
              Uses : actions / checkout@v3

          - name : setup Node.js 
              Uses : actions/ setup - node@v3
               With : 
                   Node - version : $  
{{matrix node - version}}

            - name : install dependencies 
                   Run : npm install

             - name : start application 
                    run : npm start
