name: deploy on: push: branches: # Pushing to the `master` branch # will trigger our workflow - master paths-ignore: # Ignore files and folders - 'bin/**' - 'readme.html' concurrency: #maximum of one deployment in progress and one deployment pending at a time group: ${{ github.workflow }}-${{ github.ref }} cancel-in-progress: true permissions: 


