"name: deploy
on:
  push:
    branches:
      # Pushing to the `master` branch
      # will trigger our workflow
      - master
    paths-ignore:
      # Ignore files and folders
        - 'bin/**'
        - 'readme.html'
concurrency:
  #maximum of one deployment in progress and one deployment pending at a time
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  actions: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # Checkout our repository under `${GITHUB_WORKSPACE}`,
        # so our workflow can access it
        uses: actions/checkout@v4
        with:
          # Fetch the entire Git history. 
          fetch-depth: 0

      - name: Deploy via SFTP
          #Deploy via FTP details
          uses: actions/checkout@v4
          with:
            host: ${{ secrets.MW_FTP_SERVER }}
            port: ${{ secrets.MW_FTP_PORT }}
            user: ${{ secrets.MW_FTP_USER }}
            pass: ${{ secrets.MW_FTP_PASS }}
            remoteDir: '/httpdocs'
            options: '--verbose'
